import { SQLDatabase } from "encore.dev/storage/sqldb";

// Each Encore service must import the db and create its own instance of a PrismaClient, e.g:
// import db from "../dbs/main";
// import { PrismaClient } from "../dbs/main/generated/client";
//
// export const prisma = new PrismaClient({ datasources: { db: {url: db.connectionString}}});
//
// migration files will be automatically generated by Prisma on build
// more databases can be generated by copying the structure of this directory
// the client will be automatically generated on build and placed in the ./main/generated/client module
//
export default new SQLDatabase("main", {
  migrations: {
    path: "./main/migrations",
    source: "prisma",
  },
});
