import { SQLDatabase } from "encore.dev/storage/sqldb";

// Each Encore service must import the db and create its own instance of a PrismaClient, e.g:
// import { db } from "../database/database";
// import { PrismaClient } from "../database/generated/client";
//
// export const prisma = new PrismaClient({ datasources: { db: {url: db.connectionString}}});
//
// migration files will be automatically generated by Prisma during deployment
// more databases can be generated by copying the structure of this directory
export const db = new SQLDatabase("database", {
  migrations: {
    path: "./migrations",
    source: "prisma",
  },
});
