import { SQLDatabase } from "encore.dev/storage/sqldb";

// Each Encore service must import the db and create it's own instance of a PrismaClient, e.g:
// import { db } from "../database/database";
// import { PrismaClient } from "@prisma/client";
//
// export const prisma = new PrismaClient({ datasources: { db: {url: db.connectionString}}});
//
// migration files will be automatically generated by Prisma during deployment
export const db = new SQLDatabase("database", {
  migrations: {
    path: "./prisma/migrations",
    source: "prisma",
  },
});
